CREATE TABLE FILES(
ID NUMBER NOT NULL,
FILE_NAME NVARCHAR2(10) NOT NULL,
FILE_FORMAT NVARCHAR2(50),
FILE_SIZE NUMBER,
STORAGE_ID NUMBER,
CONSTRAINT FILE_ID PRIMARY KEY(ID),
CONSTRAINT STORAGE_ID_FK FOREIGN KEY (STORAGE_ID) REFERENCES STORAGE(ID)
);